services:
    digester:
        image: metakgporg/slack-archive-digester
        container_name: slack-archive-digester
        build:
            context: "./digester"
            args:
                ZIPFILE_PATH: ${ZIPFILE_PATH}
        environment:
            - TUMMY_USERNAME=${TUMMY_USERNAME}
            - TUMMY_PASSWORD=${TUMMY_PASSWORD}
            - TUMMY_DB=${TUMMY_DB}
            - TUMMY_PORT=${TUMMY_PORT}
            - TUMMY_HOST=${TUMMY_HOST}
        networks:
            - metaploy-private-network

    excretor:
        image: metakgporg/slack-archive-excretor
        container_name: slack-archive-excretor
        build: "./excretor"
        restart: always
        environment:
            - EXCRETOR_PORT=${EXCRETOR_PORT}
            - TUMMY_USERNAME=${TUMMY_USERNAME}
            - TUMMY_PASSWORD=${TUMMY_PASSWORD}
            - TUMMY_DB=${TUMMY_DB}
            - TUMMY_PORT=${TUMMY_PORT}
            - TUMMY_HOST=${TUMMY_HOST}
            - STATIC_ASSETS_DIR=${STATIC_ASSETS_DIR}
            - SQLX_OFFLINE=true
            - SLACK_CLIENT_ID=${SLACK_CLIENT_ID}
            - SLACK_CLIENT_SECRET=${SLACK_CLIENT_SECRET}
            - SLACK_REDIRECT_URI=${SLACK_REDIRECT_URI}
            - SLACK_SIGNING_SECRET=${SLACK_SIGNING_SECRET}
            - SLACK_AUTH_ENABLE=${SLACK_AUTH_ENABLE}
        networks:
            metaploy-network:
                aliases:
                    - slack-archive
            metaploy-private-network:
        volumes:
            - nginx-config-volume:/etc/nginx/sites-enabled

networks:
    metaploy-network:
        external: true
        name: metaploy-network
    metaploy-private-network:
        external: true
        name: metaploy-private-network

volumes:
    nginx-config-volume:
        external: true
        name: metaploy-nginx-config-volume
