services:
    excretor:
        build: "./excretor"
        restart: always
        environment:
            - EXCRETOR_PORT=${EXCRETOR_PORT}
            - TUMMY_USERNAME=${TUMMY_USERNAME}
            - TUMMY_PASSWORD=${TUMMY_PASSWORD}
            - TUMMY_DB=tummy
            - TUMMY_PORT=${TUMMY_PORT}
            - TUMMY_HOST=tummy
            - STATIC_ASSETS_DIR=${STATIC_ASSETS_DIR}
            - SQLX_OFFLINE=true
        ports:
            - "${EXCRETOR_PORT}:${EXCRETOR_PORT}"
        networks:
            metaploy-network:
                aliases:
                    - slack-archive
            metaploy-private-network:
        volumes:
            - nginx-config-volume:/etc/nginx/sites-enabled

networks:
    metaploy-network:
        external: true
        name: metaploy-network
    metaploy-private-network:
        external: true
        name: metaploy-private-network

volumes:
    nginx-config-volume:
        external: true
        name: metaploy-nginx-config-volume
